#!/usr/bin/env bash
type gnome-terminal >/dev/null 2>&1 \
  && gnome-terminal -- bash --init-file "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/vendor/bin/project-bootstrap" \
  || bash --init-file "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/vendor/bin/project-bootstrap"
